---
- name: Set Up Security Measures
  hosts: localhost
  tasks:
    - name: Install cert-manager
      shell: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.15.2/cert-manager.yaml

    - name: Configure Let's Encrypt ClusterIssuer
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: letsencrypt-prod
            namespace: cert-manager
          spec:
            acme:
              server: https://acme-v02.api.letsencrypt.org/directory
              email: thearethra@gmail.com
              privateKeySecretRef:
                name: letsencrypt-prod
              solvers:
              - http01:
                  ingress:
                    class: nginx

    - name: Apply Ingress with TLS
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: socks-shop-ingress
            namespace: default
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
          spec:
            tls:
            - hosts:
              - geegeeg.blogspot.com
              secretName: socks-shop-tls
            rules:
            - host: geegeeg.blogspot.com
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: front-end
                      port:
                        number: 80

    - name: Apply NetworkPolicy
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: allow-socks-shop
            namespace: default
          spec:
            podSelector:
              matchLabels:
                app: socks-shop
            policyTypes:
            - Ingress
            ingress:
            - from:
              - podSelector:
                  matchLabels:
                    app: socks-shop
              ports:
              - protocol: TCP
                port: 80
