apiVersion: networking.k8s.io/v1  # Specifies the API version for the NetworkPolicy resource
kind: NetworkPolicy  # Resource type is NetworkPolicy, which controls the network access to and from pods
metadata:
  name: allow-socks-shop  # Name of the NetworkPolicy
  namespace: default  # The namespace where the NetworkPolicy is applied
spec:
  podSelector:
    matchLabels:
      app: socks-shop  # Selects the pods to which this NetworkPolicy applies, based on their labels
  policyTypes:
  - Ingress  # Specifies that this policy controls incoming (ingress) traffic
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: socks-shop  # Allows incoming traffic from pods with the same label 'app: socks-shop'
    ports:
    - protocol: TCP  # Specifies the protocol to allow, in this case, TCP
      port: 80  # The port on which to allow incoming traffic
