apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: socks-shop
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: socks-shop
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    interval: 30s
